---
- name: Add VirtualBox Keys
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc state=present

- apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present

- name: Add VirtualBox Repo
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian yakkety contrib'

- name: Install DKMS
  apt: name=dkms state=present

- name: Install VirtualBox
  apt: name=virtualbox-5.1 state=present
